sudo: required

services:
- docker

language: bash

branches:
  only:
  - master

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  # build
  - docker-compose build
  # run
  - docker-compose up -d spotweb
  - docker-compose ps
  - docker exec dockerarmspotweb_spotweb_1 ls
